Modify openapi description
openearthplatforminitiative/crop-health-api pull request #10
Opened 2024-06-20 12:51 UTC by daniejoh

- Changes openapi description to show three different endpoints, one for each model.
- Adds swagger on /docs

2024-06-20 13:02 UTC, daniejoh commented
Not sure why torch_serve fails to build. Have not changed anything in that folder.

2024-06-21 08:53 UTC, giltinde requested changes
Looks good, one small change requested

2024-06-21 08:53 UTC, giltinde commented on crop_health_api/custom_openapi.py
> +                    "Predicted class confidences, all summing to 1.0. Actual class names and number of returned classes may vary.",
Given that we now have separate endpoints for each model, the text about class names varying can be removed.

2024-06-21 09:41 UTC, giltinde approved these changes

2024-06-21 11:11 UTC, giltinde approved these changes

2024-06-21 11:29 UTC, merged