Adds FastAPI as middleware for Torchserve
openearthplatforminitiative/crop-health-api pull request #24
Opened 2024-08-16 13:02 UTC by daniejoh

This gives us full control of the response of torchserve. The purpose is to ensure that the response type is application/json

2024-08-16 13:03 UTC, daniejoh commented
Still need to fix traefik, as now all requests should go through FastAPI

2024-08-19 09:51 UTC, kstigen requested changes

2024-08-19 09:51 UTC, kstigen commented on deployment/kubernetes/crop-health-api.yaml
> +    match: Path(`/crop-health/redoc`) || Path(`/crop-health/openapi.json`) || Path(`/crop-health/docs`) || PathPrefix(`/crop-health`) && !PathPrefix(`/crop-health/metrics`)
Is this necessary to keep still? Aren't all requests going through fastapi, so this can be simplified?

2024-08-19 09:51 UTC, kstigen commented on crop_health_api/__main__.py
> +        response = requests.get(f"http://{torchserve_domain}:8080/ping")
The requests library does not support asyncio, so the fastapi async nature is not being fully utilized here.
Suggestion: Replace the requests library with httpx which do support asyncio. See weather-api for examples.

2024-08-19 09:51 UTC, kstigen commented on crop_health_api/__main__.py
> +    if settings.api_domain == "localhost":
This codeblock is duplicated in the ping-method. Can this be refactored to a common function?

2024-08-30 11:32 UTC, kstigen approved these changes

2024-09-02 10:41 UTC, merged